spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testspringdata
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #指定数据库
    database: mysql
    #打印sql
    show-sql: true
    hibernate:
      #开启数据库更新表
      ddl-auto: update
      #指定命名策略
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        #Hibernate方言
        dialect: org.hibernate.dialect.MySQL5Dialect